name = "cf-proxyip-us"
main = "worker.js"
compatibility_date = "2026-05-27"
workers_dev = false
preview_urls = false

[observability]
enabled = true

[[kv_namespaces]]
binding = "PROXYIP_KV"
id = "6d911271a65f4e67a39e22d991edb961"
